# Site settings
title: Karate
description: Test Automation Made Simple.
twitter_username: getkarate
github_username: ptrthomas

# Theme
remote_theme: pmarsceill/just-the-docs

# Theme settings
search_enabled: true
aux_links:
    "Karate on Github":
        - "//github.com/karatelabs/karate"
    "Karate Labs":
        - "//karatelabs.io"        
