name: delete-workflow-runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'no. of days'
        required: true
        default: 30
      minimum_runs:
        description: 'minimum runs to keep (per workflow)'
        required: true
        default: 6
        
#  push:
#    branches: [ develop ]        

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          # retain_days: 30
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          # keep_minimum_runs: 6
