name: maven-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        default: 'X.X.X.RCX'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: set up jdk 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: set maven version
      run: |
        mvn versions:set versions:commit -B -ntp -DnewVersion=${{ github.event.inputs.version }}
    - name: docker build
      run: |
        mvn clean install -B -ntp -DskipTests -P pre-release
        ./build-docker.sh
    - name: docker login
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: |        
        docker tag karate-chrome ptrthomas/karate-chrome:${{ github.event.inputs.version }}
        docker tag karate-chrome ptrthomas/karate-chrome:latest
        docker push ptrthomas/karate-chrome:${{ github.event.inputs.version }}
        docker push ptrthomas/karate-chrome:latest
    - name: maven deploy to central
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: |
        mvn -B -ntp deploy -DskipTests -P pre-release,release
    - name: maven build binaries
      run: |
        mvn package -DskipTests -P fatjar -f karate-core/pom.xml
        mvn package -DskipTests -P fatjar -f karate-robot/pom.xml
    - name: upload binaries
      uses: actions/upload-artifact@v3
      with: 
        name: karate-release-${{ github.event.inputs.version }}
        retention-days: 5 
        path: |
          karate-core/target/*.jar
          karate-core/target/*.zip
          karate-robot/target/*.jar  
